import Head from 'next/head';
import { GET_ALL_PRODUCTS } from '../graphql/Queries';
import { useQuery } from '@apollo/client';
import Converter from '../components/converter/Converter';
import { useState } from 'react';
import Products from '../components/Products';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='mb-20'>
        <h1 className='text-5xl font-bold text-center'>Hello</h1>
        {/* <div className='flex flex-col'>
        {data.getAllProducts.slice(0, 5).map((product, id) => (
          <div key={id}>
            <h1>Name: {product.name}</h1>
            <p>Barcode: {product.barcode}</p>
            <p>Exp Date: {product.expDate}</p>
          </div>
        ))}
      </div> */}
        <Products></Products>
        {/* <Converter></Converter> */}
      </main>
    </div>
  );
}
